name: Build Assets

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.REPO_PAT }}

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        grunt
        
    - name: Commit assets
      run: |
        git config --global user.name 'Github'
        git config --global user.email 'cannarocks@users.noreply.github.com'
        git commit -am "chore: executed grunt command"
        git push
